# -*- coding: utf-8 -*-
"""primeiro algoritmo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12x0XaWvTxrhi2MxHK61cO5d_2mVltE2d
"""

escolha = int(input('Quantas operações matemáticas você quer fazer? '))
contador = 0
while True:
    num1 = int(input('Digite um número: '))
    num2 = int(input('Digite outro número: '))
    print('[1] Soma'
        '\n[2] Divisão'
        '\n[3] Multiplicação'
        '\n[4] Subtração')
    operaçao = int(input('Qual operação matemática: '))
    if operaçao == 1:
        soma = num1 + num2
        print(f'{num1} + {num2} = {soma}')
    elif operaçao == 2:
        divisao = num1 / num2
        print(f'{num1} ÷ {num2} = {divisao}')
    elif operaçao == 3:
        multiplicaçao = num1 * num2
        print(f'{num1} x {num2} = {multiplicaçao}')
    else:
        subtracao = num1 - num2
        print(f'{num1} - {num2} = {subtracao}')
    contador += 1
    if contador >= escolha:
        break